### PR TITLE
Updates to better conform to WP Coding Standards

### LINKED ISSUE #118: Update code to conform to WP coding standards
### Is your enhancement related to a problem? Please describe.

Creating this to better track the progress of updating the code to better comply with WP coding standards, see https://github.com/10up/eight-day-week/pull/117#issuecomment-1587677103

* Update (6/28/23) - The remaining items left are a little more involved, see https://github.com/10up/eight-day-week/issues/118#issuecomment-1591666342

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bmarshall511**
### Description of the Change

Lots of code updates to better conform to WordPress Coding Standards.

Closes #118 

### Changelog Entry

> Fixed - Misc. code updates to better conform to WordPress Coding Standards

### Credits

Props @bmarshall511 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by Sidsector9** [comment]
@bmarshall511 I [confirmed here](https://github.com/Sidsector9/eight-day-week/actions) that the tests pass on `develop` but are failing on this branch. Can you fix them?

**Comment by bmarshall511** [comment]
@Sidsector9 Fixed the failing test. There's still a handful of files that still need to be touched to better conform to standards, but leaving as is for now until https://github.com/10up/eight-day-week/pull/117 gets merged to avoid a bunch of potential conflicts.

Side note, this handles about 90% of the coding standard errors. There's still some that'll require a larger lift (i.e restructuring classes, adding nonces, renaming hooks, etc.), but probably better to handle those in a separate PR.

**Review by Sidsector9 — APPROVED** [review]
That's no problem, we can handle the remaining 10% in a separate PR. Thanks for fixing the tests 👍

**Review by Sidsector9 — DISMISSED** [review]

**Comment by bmarshall511** [comment]
> @Sidsector9 Fixed the failing test. There's still a handful of files that still need to be touched to better conform to standards, but leaving as is for now until #117 gets merged to avoid a bunch of potential conflicts.
> 
> Side note, this handles about 90% of the coding standard errors. There's still some that'll require a larger lift (i.e restructuring classes, adding nonces, renaming hooks, etc.), but probably better to handle those in a separate PR.

@Sidsector9 Got this updated with `develop` and fixed those handful of files.

**Review by Sidsector9 — APPROVED** [review]

**Pull request merged**
