### PR TITLE
upkeep/15: add PHPCS and PHP Compatibility actions

### LINKED ISSUE #15: Add phpcs linting
See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

Note: depending on the volume of issues found we can either correct them as part of this issue or spin up a separate issue to address them.

### PR DESCRIPTION
**Pull request by Sidsector9**
### Description of the Change

Adds PHPCS and PHP Compatibility actions

Closes #15

### Changelog Entry

> Added - Github Action to check PHP coding and compatibility standards.

### Credits

Props @jeffpaul @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by cadic — CHANGES_REQUESTED** [review]
@Sidsector9 thank you for this change.

I wonder, could we also rename .wpcs.xml to the one of the [Default Configuration File](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file) names, so the PHP_CodeSniffer in the IDE on developer's local machine will read the configuration and highlight the rules in the editor?

**Comment by jeffpaul** [comment]
@Sidsector9 any thoughts on Max's comment above?

**Comment by vikrampm1** [comment]
@Sidsector9 this is awaiting your response, please take a look when you get a chance.

**Comment by Sidsector9** [comment]
@cadic thanks for the suggestion, makes sense 👍

**Review by faisal-alvi — APPROVED** [review]
@Sidsector9 LGTM, however, there are errors reported in the "PHP Standards Scrutinizer" action, we are good if those are ignored intentionally.

**Comment by Sidsector9** [comment]
The PHPCS errors can be handled in a separate PR. This can go ahead.

**Pull request merged**
